sensor_kit_base_link:
  camera0/camera_link:
    x: 0.7 #0.10731
    y: 0.0 #0.56343
    z: 0.0 #-0.27697
    roll: 0.0 #-0.025
    pitch: 0.0 #0.315
    yaw: 0.0 #1.035
  camera1/camera_link:
    x: 0.0 #-0.10731
    y: 0.0 #-0.56343
    z: 0.0 #-0.27697
    roll: 0.0 #-0.025
    pitch: 0.0 #0.32
    yaw: 0.0 #-2.12
  camera2/camera_link:
    x: 0.0 #0.10731
    y: 0.0 #-0.56343
    z: 0.0 #-0.27697
    roll: 0.0 #-0.00
    pitch: 0.0 #0.335
    yaw: 0.0 #-1.04
  camera3/camera_link:
    x: 0.0 #-0.10731
    y: 0.0 #0.56343
    z: 0.0 #-0.27697
    roll: 0.0
    pitch: 0.0 #0.325
    yaw: 0.0 #2.0943951
  camera4/camera_link:
    x: 0.0 #0.07356
    y: 0.0
    z: 0.0 #-0.0525
    roll: 0.0
    pitch: 0.0 #-0.03
    yaw: 0.0 #-0.005
  camera5/camera_link:
    x: 0.0 #-0.07356
    y: 0.0
    z: 0.0 #-0.0525
    roll: 0.0
    pitch: 0.0 #-0.01
    yaw: 0.0 #3.125
  traffic_light_right_camera/camera_link:
    x: 0.0 #0.05
    y: 0.0 #-0.0175
    z: 0.0 #-0.1
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  traffic_light_left_camera/camera_link:
    x: 0.0 #0.05
    y: 0.0 #0.0175
    z: 0.0 #-0.1
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  velodyne_top_base_link:
    x: 0.0
    y: 0.0
    z: 0.8
    roll: 0.0
    pitch: 0.0
    yaw: 0.0 #1.575
  velodyne_left_base_link:
    x: -0.5 #0.0
    y: 0.0 #0.56362
    z: 0.8 #-0.30555
    roll: 0.0 #-0.02
    pitch: 0.0 #0.71
    yaw: 0.0 #1.575
  velodyne_right_base_link:
    x: 0.5 #0.0
    y: 0.0 #-0.56362
    z: 0.8 #-0.30555
    roll: 0.0 #-0.01
    pitch: 0.0 #0.71
    yaw: 0.0 #-1.580
  gnss_link:
    x: 0.0 #-0.1
    y: 0.0
    z: 0.8 #-0.2
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  tamagawa/imu_link:
    x: 0.0
    y: 0.0
    z: 0.8 #0.0
    roll: 0.0 #3.14159265359
    pitch: 0.0
    yaw: 0.0 #3.14159265359
